---
title: "b"
author: "Siyuan Sang"
date: "2021/1/28"
output: html_document
---

```{r load library and read in data, warning=FALSE, message=FALSE, include=FALSE}
library(tidyverse)
library(dbplyr)
library(ggplot2)
library(haven)
anes_dat<-read_sav("C:/Users/13605/Documents/GitHub/Spring2021-Project1-aladhe/data/anes_timeseries_2016.sav")
```


```{r define the loyal variable, echo=FALSE}
anes_dat$loyal<-ifelse((anes_dat$V161006==1&(anes_dat$V161027==1|anes_dat$V162034a==1)&(anes_dat$V161047==1|anes_dat$V162047==1)),"Democrats loyal",ifelse((anes_dat$V161006==2&(anes_dat$V161027==2|anes_dat$V162034a==2)&(anes_dat$V161047==2|anes_dat$V162047==2)),"Republican loyal","Not loyal to main parties"))
table(anes_dat$loyal)
```



```{r echo=FALSE}
anes_dat$politics<-as.factor(anes_dat$V162256)
 ggplot(anes_dat, aes(x=politics,  group=loyal)) + 
    geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count",position=position_dodge(0.7),width=0.5) +
   geom_text(aes( label = scales::percent(..prop..),
                   y= ..prop.. ), stat= "count", vjust = -.5) +
    labs(title="Attention to politics",y ="Percent",fill="politics") +
    facet_grid(~loyal) +
    scale_fill_discrete(name="Attention to politics",
                         breaks=c("1", "2", "3","4","5","6","7","8"),
                         labels=c("Refused", "Don't know", "No post data","No post-election interview","Very interested","Somewhat interested","Not very interested","Not at all interested"))+
    scale_y_continuous(labels = scales::percent)
```


```{r echo=FALSE}
anes_dat$partic<-ifelse(anes_dat$V162010 ==1|anes_dat$V162011 ==1|anes_dat$V162012==1|anes_dat$V162013==1|anes_dat$V162014==1,"active","inactive")
ggplot(anes_dat, aes(x=partic,  group=loyal)) + 
    geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count",position=position_dodge(0.7),width=0.5) +
   geom_text(aes( label = scales::percent(..prop..),
                   y= ..prop.. ), stat= "count", vjust = -.5) +
    labs(title="Attention to politics",y ="Percent",fill="partic") +
    facet_grid(~loyal) +
    scale_fill_discrete(name="Political participation",
                         breaks=c("1", "2"),
                         labels=c("Active", "Inactive"))+
    scale_y_continuous(labels = scales::percent)
```